### PR TITLE
Improve createSelector title

### PR DESCRIPTION
**Pull request by weblancaster**
Although the duplicated title is intended it was confusing at first, moving to description.

### CODE REVIEW

**Comment by ellbee** [comment]
Yeah, good point. Thanks for the PR. I have no time at all to look at this for the next couple of days, but I intend to merge (I would just like to think if I want to tweak the wording a bit).

**Comment by weblancaster** [comment]
Ok cool.. yeah this is no more than 2mins @ellbee 

thanks

**Comment by mindjuice** [comment]
I would leave the extra function definition and just update the wording a bit to clarify:

    Takes one or more selectors (or an array of selectors) whose values are computed and passed as arguments to `resultFn`.

Alternatively to avoid the passive voice:

    Takes one or more selectors, or an array of selectors, computes their values and passes them as arguments to `resultFn`.

**Comment by ellbee** [comment]
@weblancaster @mindjuice Thanks for the input, I've sort of ended up doing something in the middle.

**Pull request merged**
